export const hero1 = {
  id: 1,
  appearance: {
    eyeColor: "black",
    gender: "male",
    hairColor: "black",
    height: ["6ft", "190cm"],
    race: "human",
    weight: ["5pd", "100kg"],
  },
  biography: {
    aliases: ["1", "2"],
    alignment: "good",
    alterEgos: "string",
    firstAppearance: "string",
    fullName: "string",
    placeOfBirth: "string",
    publisher: "string",
  },
  connections: { groupAffiliation: "string", relatives: "string" },
  images: {
    lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/1-a-bomb.jpg",
    md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/1-a-bomb.jpg",
    sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/1-a-bomb.jpg",
    xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/1-a-bomb.jpg",
  },
  name: "A-Bomb",
  powerstats: {
    combat: 64,
    durability: 80,
    intelligence: 38,
    power: 24,
    speed: 17,
    strength: 100,
  },
  slug: "1-a-bomb",
  work: {
    base: "-",
    occupation: "Musician, adventurer, author; formerly talk show host",
  },
  isFavorite: false,
};
export const hero2 = {
  id: 2,
  appearance: {
    eyeColor: "black",
    gender: "male",
    hairColor: "black",
    height: ["6ft", "190cm"],
    race: "human",
    weight: ["5pd", "100kg"],
  },
  biography: {
    aliases: ["1", "2"],
    alignment: "good",
    alterEgos: "string",
    firstAppearance: "string",
    fullName: "string",
    placeOfBirth: "string",
    publisher: "string",
  },
  connections: { groupAffiliation: "string", relatives: "string" },
  images: {
    lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/1-a-bomb.jpg",
    md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/1-a-bomb.jpg",
    sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/1-a-bomb.jpg",
    xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/1-a-bomb.jpg",
  },
  name: "Abe Sapien",
  powerstats: {
    combat: 64,
    durability: 80,
    intelligence: 38,
    power: 24,
    speed: 17,
    strength: 100,
  },
  slug: "1-abe-sapien",
  work: {
    base: "-",
    occupation: "Musician, adventurer, author; formerly talk show host",
  },
  isFavorite: false,
};
export const hero3 = {
  id: 3,
  appearance: {
    eyeColor: "black",
    gender: "male",
    hairColor: "black",
    height: ["6ft", "190cm"],
    race: "human",
    weight: ["5pd", "100kg"],
  },
  biography: {
    aliases: ["1", "2"],
    alignment: "good",
    alterEgos: "string",
    firstAppearance: "string",
    fullName: "string",
    placeOfBirth: "string",
    publisher: "string",
  },
  connections: { groupAffiliation: "string", relatives: "string" },
  images: {
    lg: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/1-a-bomb.jpg",
    md: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/1-a-bomb.jpg",
    sm: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/1-a-bomb.jpg",
    xs: "https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/1-a-bomb.jpg",
  },
  name: "Abin Sur",
  powerstats: {
    combat: 64,
    durability: 80,
    intelligence: 38,
    power: 24,
    speed: 17,
    strength: 100,
  },
  slug: "3-abin-sur",
  work: {
    base: "-",
    occupation: "Musician, adventurer, author; formerly talk show host",
  },
  isFavorite: true,
};

export const heroesArray = [hero1, hero2, hero3];
