name: Node.js CI
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.13"
      - run: |
          git config --global user.email "meleshkorostyslav@gmail.com"
          git config --global user.name "Rostyslav Meleshko"
      - run: npm install
      - run: npm run deploy
#      - name: Deploy
#        uses: rostyslav-meleshko/ghaction-github-pages@v1
#        with:
#          target_branch: gh-pages
#          build_dir: build
